apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foosts.wxcontroller.k8s.io
spec:
  group: wxcontroller.k8s.io
  version: v1alpha1
  names:
    kind: FooSts
    plural: foosts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
